import { describe, expect, it } from "vitest";
import * as raw from "../src/raw.js";
import {
  AccountValidator,
  Catalogue,
  ChatApi,
  ChatValidator,
  CURRENCY_UUIDS,
  decodeValorantPresence,
  defaultCatalogueDir,
  defaultResponseCacheDir,
  ENTITLEMENT_ITEM_TYPES,
  FileCatalogueStore,
  FileResponseCache,
  ForbiddenHostError,
  HttpGateway,
  LoadoutValidator,
  LoadoutWriter,
  MatchValidator,
  MemoryCatalogueCache,
  parseFrame,
  PartyValidator,
  RegionUnknownError,
  RiotApi,
  RiotApiError,
  RiotClientError,
  RiotClientLocalApi,
  RiotClientNotReadyError,
  RiotClientNotRunningError,
  RiotSocket,
  Session,
  SessionManager,
  StoreValidator,
  ValidationError,
  ValorantApi,
} from "../src/raw.js";
import type {
  BlockedPlayer,
  BuyTarget,
  BuyValidationResult,
  Conversation,
  Cost,
  CustomGameSettings,
  Friend,
  FriendRequest,
  HttpFetchFn,
  LoadoutChange,
  LoadoutGunChange,
  LocalApiFetchFn,
  LocalApiResponse,
  LocalEntitlementsToken,
  LocalSessionInfo,
  OwnedItems,
  PartyAction,
  PartyActionRequest,
  RawBlockedPlayer,
  RawBlockedResponse,
  RawChatFriend,
  RawChatMessage,
  RawChatPresence,
  RawChatSession,
  RawConversation,
  RawConversationsResponse,
  RawFriendRequest,
  RawFriendRequestsResponse,
  RawFriendsResponse,
  RawMessagesResponse,
  RawParticipant,
  RawParticipantsResponse,
  RawPresencesResponse,
  RiotAccountXpHistoryItem,
  RiotAccountXpResponse,
  RiotAccountXpSource,
  RiotActiveExpression,
  RiotClientConfigResponse,
  RiotCompetitiveUpdate,
  RiotCompetitiveUpdatesResponse,
  RiotContentEvent,
  RiotContentResponse,
  RiotContentSeason,
  RiotContractsResponse,
  RiotCoreGameLoadoutEntry,
  RiotCoreGameLoadoutItem,
  RiotCoreGameLoadoutsResponse,
  RiotCoreGameMatchResponse,
  RiotCoreGamePlayer,
  RiotCoreGamePlayerResponse,
  RiotCoreGameSocketItem,
  RiotCredentialsResolver,
  RiotCustomGameConfigsResponse,
  RiotDamage,
  RiotEntitlementItem,
  RiotEntitlementsByType,
  RiotEntitlementsResponse,
  RiotEventType,
  RiotFavoritesResponse,
  RiotFinishingDamage,
  RiotFrame,
  RiotKill,
  RiotLeaderboardPlayer,
  RiotLeaderboardResponse,
  RiotLoadoutGun,
  RiotLoadoutGunPut,
  RiotLoadoutIdentity,
  RiotLoadoutPutBody,
  RiotLoadoutResponse,
  RiotLoadoutSpray,
  RiotMatchDetailsResponse,
  RiotMatchHistoryItem,
  RiotMatchHistoryResponse,
  RiotMatchInfo,
  RiotMatchPlayer,
  RiotMatchTeam,
  RiotMmrResponse,
  RiotNameResponse,
  RiotOffersResponse,
  RiotOrderResponse,
  RiotPartyCustomGameData,
  RiotPartyCustomGameMembership,
  RiotPartyMember,
  RiotPartyPlayerInvite,
  RiotPartyPlayerResponse,
  RiotPartyRequestItem,
  RiotPartyResponse,
  RiotPenaltiesResponse,
  RiotPenaltyItem,
  RiotPlayerAbilityCasts,
  RiotPlayerStats,
  RiotPregameMatchResponse,
  RiotPregamePlayer,
  RiotPregamePlayerResponse,
  RiotQueueConfigItem,
  RiotQueueConfigsResponse,
  RiotQueueSkills,
  RiotRoundPlayerStats,
  RiotRoundResult,
  RiotSeasonalInfo,
  RiotSessionResponse,
  RiotSocketCredentials,
  RiotSocketOptions,
  RiotStorefrontResponse,
  RiotStoreOffer,
  RiotStoreReward,
  RiotTierDetail,
  RiotWalletResponse,
  SessionInit,
  SessionManagerOptions,
  Store,
  StoredCatalogue,
  StoreItem,
  ValorantApiAgent,
  ValorantApiBuddy,
  ValorantApiBuddyLevel,
  ValorantApiBundle,
  ValorantApiCatalogueData,
  ValorantApiChroma,
  ValorantApiContentTier,
  ValorantApiContract,
  ValorantApiCurrency,
  ValorantApiLevelBorder,
  ValorantApiMap,
  ValorantApiMission,
  ValorantApiPlayerCard,
  ValorantApiPlayerTitle,
  ValorantApiSeason,
  ValorantApiSkin,
  ValorantApiSkinLevel,
  ValorantApiSpray,
  ValorantApiTier,
  ValorantApiWeapon,
  ValorantPresence,
  Wallet,
  WebSocketConstructor,
  WebSocketLike,
} from "../src/raw.js";

describe("raw entry point", () => {
  it("imports and defines every named export", () => {
    const exportsToVerify: Array<[string, unknown]> = [
      ["SessionManager", SessionManager],
      ["Session", Session],
      ["HttpGateway", HttpGateway],
      ["RiotApi", RiotApi],
      ["RiotClientLocalApi", RiotClientLocalApi],
      ["ChatApi", ChatApi],
      ["RiotSocket", RiotSocket],
      ["parseFrame", parseFrame],
      ["ValorantApi", ValorantApi],
      ["MemoryCatalogueCache", MemoryCatalogueCache],
      ["Catalogue", Catalogue],
      ["FileCatalogueStore", FileCatalogueStore],
      ["defaultCatalogueDir", defaultCatalogueDir],
      ["FileResponseCache", FileResponseCache],
      ["defaultResponseCacheDir", defaultResponseCacheDir],
      ["decodeValorantPresence", decodeValorantPresence],
      ["LoadoutValidator", LoadoutValidator],
      ["ChatValidator", ChatValidator],
      ["PartyValidator", PartyValidator],
      ["AccountValidator", AccountValidator],
      ["MatchValidator", MatchValidator],
      ["StoreValidator", StoreValidator],
      ["LoadoutWriter", LoadoutWriter],
      ["ENTITLEMENT_ITEM_TYPES", ENTITLEMENT_ITEM_TYPES],
      ["CURRENCY_UUIDS", CURRENCY_UUIDS],
      ["RiotClientError", RiotClientError],
      ["RiotClientNotRunningError", RiotClientNotRunningError],
      ["RiotClientNotReadyError", RiotClientNotReadyError],
      ["RegionUnknownError", RegionUnknownError],
      ["ForbiddenHostError", ForbiddenHostError],
      ["RiotApiError", RiotApiError],
      ["ValidationError", ValidationError],
    ];

    for (const [name, value] of exportsToVerify) {
      expect(value, `Expected export ${name} to be defined`).toBeDefined();
    }
  });

  it("ensures every value export from raw module is defined", () => {
    const keys = Object.keys(raw);
    expect(keys.length).toBeGreaterThan(0);
    for (const key of keys) {
      expect(raw[key as keyof typeof raw], `Export ${key} must not be undefined`).toBeDefined();
    }
  });

  it("verifies compile-time type imports from raw entry point", () => {
    type Assert<T, Expected> = T extends Expected ? true : false;
    const _check: Assert<
      [
        SessionManagerOptions,
        SessionInit,
        HttpFetchFn,
        LocalApiResponse,
        LocalEntitlementsToken,
        LocalSessionInfo,
        LocalApiFetchFn,
        RiotEventType,
        RiotFrame,
        RiotSocketCredentials,
        RiotCredentialsResolver,
        WebSocketLike,
        WebSocketConstructor,
        RiotSocketOptions,
        StoredCatalogue,
        LoadoutChange,
        LoadoutGunChange,
        PartyAction,
        PartyActionRequest,
        BuyTarget,
        BuyValidationResult,
        RiotLoadoutGunPut,
        RiotLoadoutPutBody,
        OwnedItems,
        BlockedPlayer,
        Conversation,
        Cost,
        CustomGameSettings,
        Friend,
        FriendRequest,
        Store,
        StoreItem,
        ValorantPresence,
        Wallet,
        RawChatFriend,
        RawFriendsResponse,
        RawChatPresence,
        RawPresencesResponse,
        RawFriendRequest,
        RawFriendRequestsResponse,
        RawBlockedPlayer,
        RawBlockedResponse,
        RawConversation,
        RawConversationsResponse,
        RawChatMessage,
        RawMessagesResponse,
        RawChatSession,
        RawParticipant,
        RawParticipantsResponse,
        ValorantApiSkinLevel,
        ValorantApiChroma,
        ValorantApiSkin,
        ValorantApiWeapon,
        ValorantApiPlayerCard,
        ValorantApiPlayerTitle,
        ValorantApiSpray,
        ValorantApiBuddyLevel,
        ValorantApiBuddy,
        ValorantApiAgent,
        ValorantApiContentTier,
        ValorantApiCurrency,
        ValorantApiBundle,
        ValorantApiMap,
        ValorantApiTier,
        ValorantApiSeason,
        ValorantApiLevelBorder,
        ValorantApiContract,
        ValorantApiMission,
        ValorantApiCatalogueData,
        RiotEntitlementItem,
        RiotEntitlementsByType,
        RiotEntitlementsResponse,
        RiotLoadoutGun,
        RiotLoadoutSpray,
        RiotLoadoutIdentity,
        RiotActiveExpression,
        RiotLoadoutResponse,
        RiotAccountXpSource,
        RiotAccountXpHistoryItem,
        RiotAccountXpResponse,
        RiotWalletResponse,
        RiotNameResponse,
        RiotStoreReward,
        RiotStoreOffer,
        RiotStorefrontResponse,
        RiotMatchHistoryItem,
        RiotMatchHistoryResponse,
        RiotMatchInfo,
        RiotPlayerAbilityCasts,
        RiotPlayerStats,
        RiotMatchPlayer,
        RiotMatchTeam,
        RiotFinishingDamage,
        RiotKill,
        RiotDamage,
        RiotRoundPlayerStats,
        RiotRoundResult,
        RiotMatchDetailsResponse,
        RiotSeasonalInfo,
        RiotCompetitiveUpdate,
        RiotQueueSkills,
        RiotMmrResponse,
        RiotCompetitiveUpdatesResponse,
        RiotPregamePlayerResponse,
        RiotPregamePlayer,
        RiotPregameMatchResponse,
        RiotCoreGamePlayerResponse,
        RiotCoreGamePlayer,
        RiotCoreGameMatchResponse,
        RiotCoreGameSocketItem,
        RiotCoreGameLoadoutItem,
        RiotCoreGameLoadoutEntry,
        RiotCoreGameLoadoutsResponse,
        RiotPartyPlayerInvite,
        RiotPartyPlayerResponse,
        RiotPartyMember,
        RiotPartyRequestItem,
        RiotPartyCustomGameMembership,
        RiotPartyCustomGameData,
        RiotPartyResponse,
        RiotPenaltyItem,
        RiotPenaltiesResponse,
        RiotFavoritesResponse,
        RiotLeaderboardPlayer,
        RiotTierDetail,
        RiotLeaderboardResponse,
        RiotOffersResponse,
        RiotOrderResponse,
        RiotSessionResponse,
        RiotClientConfigResponse,
        RiotContentSeason,
        RiotContentEvent,
        RiotContentResponse,
        RiotQueueConfigItem,
        RiotQueueConfigsResponse,
        RiotCustomGameConfigsResponse,
        RiotContractsResponse,
      ],
      unknown
    > = true;
    expect(_check).toBe(true);
  });
});
